sudo: false
language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0.4"

before_script:
  - npm install

addons:
    code_climate:
        repo_token: 9c13ed011e726d18666a6ce0326dac56ab5d3f505932c9bf488ad9c15dc3d10c
